### ISSUE TITLE
Problem with installation

### ISSUE THREAD

**Issue by shuxx** [dcblogdev/laravel-admintw#21]
Hey, i would like to test your package but i have an issue with my installation 
First i've started a new project but when i migrate i have this error : 

`  SQLSTATE[HY000]: General error: 3780 Referencing column 'user_id' and referenced column 'id' in foreign key constraint 'audit_trails_user_id_foreign' are incompatible. (Connection: mysql, SQL: alter table `audit_trails` add constraint `audit_trails_user_id_foreign` foreign key (`user_id`) references `users` (`id`) on delete cascade)
`

**Comment by dcblogdev** [comment]
thanks, this was due to a migration order, I've corrected this now.

To manually sort rename `2014_10_12_000000_create_audit_trails_table.php` to `2014_10_13_000000_create_audit_trails_table.php`

also update the users migration for `2014_10_12_000000_create_users_table.php` to `$table->timestamp('invited_at')->nullable();`

**Comment by shuxx** [comment]
It's work now thanks :)
