### ISSUE TITLE
Passing route parameters.

### ISSUE THREAD

**Issue by d7gonzo** [dcblogdev/laravel-admintw#6]
Hi, I've been trying to build a relatively simple CRUD app with AdminTW for authentication and dashboard. I keep having to work around not having route parameters easily accessible for form processing, as the normal Livewire syntax seems to have been superseded by the AdminTW Base class. I don't see any documentation that could help me in passing route parameters the way it is documented by Livewire. I have only been able to access route parameters that are passed directly to a function, rather than a whole component. Can you advise on the syntax that replaces Livewire's syntax for `mount()`?

For example, from the Livewire site:
```
class ShowPost extends Component
{
    public $post;
 
    public function mount($id)
    {
        $this->post = Post::find($id);
    }
 
    ...
}
```
With a route such as:
```
Route::get('/post/{id}', ShowPost::class);
```
I've been banging my head against a wall trying to follow the patterns visible in other classes included with AdminTW and have come up empty handed a few too many times for comfort. Any documentation of your revised Livewire API would be most welcome.

Thank you!

**Comment by dcblogdev** [comment]
The mount on the base class acts as a contract for setting multiple things for the application.

What I tend to do is use route model binding instead. So in your example I would change the code to this:

Route: use the model name
```
Route::get('/post/{post}', ShowPost::class);
```

in livewire use the model when declaring the variable.

```php
class ShowPost extends Base
{
    public Post $post;

    public function mount()
    {
        dd($this->post);
    }

    ...
}
```

If you're writing a component for the front end where auth is not needed I would use the regular `component` instead of the `base`.

It would be great if Livewire 3 supports `construct` so that I could avoid this need of touching the base mount.

**Comment by d7gonzo** [comment]
That was the missing piece of the puzzle for me! The route model binding is sufficiently documented by Livewire but it isn't what I was looking at for passing parameters before now. This works very nicely. Thank you for the quick reply! I recommend adding this to the AdminTW documentation with a code example. It might help someone else who doesn't realize that the route model binding is necessary for route parameters in AdminTW.
